
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.clap]]
version = "4.6.6"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.6.4"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.14.1"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.9.12+spec-1.1.0"
criteria = "safe-to-deploy"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-deploy"
